### ISSUE TITLE
run run_dance_test.py error

### ISSUE THREAD

**Issue by wangtuo111** [Paulkie99/imm-jhse#1]
u_ratio = 0.05, v_ratio = 0.05, u_max = 13, v_max = 10
det_results/dance/test/dancetrack0003.txt
cam_para/DanceTrack/dancetrack0003.txt
Traceback (most recent call last):
  File "/imm-jhse-imm/run_dance_test.py", line 13, in <module>
    run_ucmc(args, det_path, cam_path, gmc_path, out_path, exp_name,dataset)
  File "/imm-jhse-imm/util/run_ucmc.py", line 166, in run_ucmc
    detector.load(cam_para, det_file,gmc_file,args.P,sigma_m=args.sigma_m)
  File "/imm-jhse-imm/detector/detector.py", line 47, in load
    self.mapper = Mapper(cam_para_file,"kitti" if kitti else "MOT17",p_alpha,dt=self.dt,sigma_m=sigma_m)
  File "/imm-jhse-imm/detector/mapper.py", line 113, in __init__
    self.process_covariance = np.load("pnoise/dancetrack0007.npy")
  File "/home/anaconda3/envs/mot/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pnoise/dancetrack0007.npy'

**Comment by Paulkie99** [comment]
Hi @wangtuo111 , thanks for your interest in our work! Sorry for not having the repo in a workable state sooner.

I have added the missing file to the repo. I forgot that we have to specify the initial process covariance, even though dynamic noise estimation is used subsequently.

I have also made some other changes and added instructions. Please pull the latest commit and let me know if you have any more issues.
